config/routes.rb
Rails.application.routes.draw do

  resources :runners do
    resources :races
  end
  root 'welcome#index'

end

app/models/race.rb
class Race < ActiveRecord::Base
  belongs_to :runner
end

app/models/runner.rb
class Runner < ActiveRecord::Base
  has_many :races
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  def index
    @runner = Runner.find(params[:runner_id])
    @races = @runner.races.all
  end
  def show
    @runner = Runner.find(params[:runner_id])
    @race = @runner.races.find(params[:id])
  end
  def new
    @runner = Runner.find(params[:runner_id])
    @race = @runner.races.new
  end
  def create
    @runner = Runner.find(params[:runner_id])
    @race = @runner.races.create(race_params)

    redirect_to runner_races_path(@runner, @races)
  end
  def edit
    @runner = Runner.find(params[:runner_id])
    @race = @runner.races.find(params[:id])
  end
  def update
    @runner = Runner.find(params[:runner_id])
    @race = @runner.races.find(params[:id])
    @race.update(race_params)

    redirect_to runner_races_path
  end
  def destroy
  @runner = Runner.find(params[:runner_id])
  @race = Race.find(params[:id])
  @race.destroy

  redirect_to runner_races_path
end
  private
  def race_params
    params.require(:race).permit(:title, :date, :time)
  end
end

app/controllers/runners_controller.rb
class RunnersController < ApplicationController
  def index
    @runners = Runner.all
  end
  def new
    @runner = Runner.new
  end
  def create
    @runner = Runner.create!(runner_params)
    redirect_to new_runner_race_path(@runner, @race)
  end
  def show
    @runner = Runner.find(params[:id])
  end
  private
  def runner_params
    params.require(:runner).permit(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/races_helper.rb
module RacesHelper
end

app/helpers/runners_helper.rb
module RunnersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Joggerlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= yield %>

</body>
</html>

app/views/races/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title></title>
</head>
<body>
  <div class="div_top">
  <h1>Edit Races</h1>
</div>

<div class="form">
  <%= form_for [@runner, @race] do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :date %><br>
    <%= f.date_field :date %>
  </p>
  <p>
    <%= f.label :time %><br>
    <%= f.text_field :time %>
  </p>
  <p>
    <%= f.submit "Update", :class => "form-button" %>
  </p>
  <% end %>
  <%= form_for [@runner, @race], method: :delete do |f| %>
  <%= f.submit "Delete", :class => "form-button" %>
  <% end %>
</div>
</body>
</html>

app/views/races/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title></title>
</head>
<body>
  <div class="container">
    <div class="div_top">
      <div class="header-text"><h1><%= @runner.name %>'s Jog Log</h1></div>
    </div>
  </div>
  <div class="content">
    <div class="styletable">
      <table class="flat-table", align="center">

        <% @runner.races.each do |race| %>
        <thead>
          <th>Race Name</th>
          <th>Date</th>
          <th>Finish Time</th>
        </thead>
        <tr>
          <td><%= race.title %></td>
          <td><%= race.date %></td>
          <td><%= race.time %></td>
          <td><%= link_to 'edit', edit_runner_race_path(@runner, race) %></td>
        </tr>
        <% end %>
      </table>
    </div>

    <div class="button"><%= link_to 'Add New Race', new_runner_race_path(@runner, @race) %>
      <%= link_to 'New Runner', new_runner_path(@runner) %>
      <%= link_to 'Home', root_path %>
    </div>
  </div>
</div>

</body>
</html>

app/views/races/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title></title>
</head>
<body>
  <div class="div_top">
    <h1>Jog Log</h1>
  </div>

  <div class="form">
    <%= form_for [@runner, @race] do |f| %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :date %><br>
      <%= f.date_field :date %>
    </p>
    <p>
      <%= f.label :time %><br>
      <%= f.text_field :time %>
    </p>
    <p>
      <%= f.submit "Submit", :class => "form-button" %>
    </p>
    <% end %>
  </div>
</body>
</html>

app/views/races/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @race.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @race.date %>
</p>
<p>
  <strong>Time:</strong>
  <%= @race.time %>
</p>

app/views/runners/index.html.erb
<h1>Races</h1>
<%= link_to 'Jog Log', new_runner_path %>
<%= link_to 'Recent races', new_race_path %>
<!-- rend form info -->

app/views/runners/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title></title>
</head>
<body>
  <div class="div_top">
    <h1>Getting Started</h1>
  </div>
  <div class="new_user_prompt">New to Jog Log? Please enter your name!</div>
  <div class="form">
    <%= form_for @runner do |f| %>
    <p class="name">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.submit "Create Runner", :class => "form-button"%>
    </p>

    <% end %>
  </div>
</body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="div_top">
    <h1>Welcome to the Jog Log</h1>
  </div>
  <p class="slogan">The Jog Log is an app that allows runners to keep track of upcoming and previous races.</br>Made for runners, by a runner.</p>
<h2 align="center"><div class="button"><%= link_to 'Enter site', new_runner_path %></div><h2>
  <div class="contactinfo">Hilary Masland | <a href="mailto:hilarymasland@gmail.com">hilarymasland@gmail.com</a> </div>
  </body>
</html>